config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#new'
  resources :users do
    resources :books
  end
  resources :books do
    resources :reviews
  end
  get '/good_books', to: 'books#good_books'

  get '/login', to: 'users#login_form', as: 'login'
  post '/login', to: 'users#login'
  delete '/logout', to: 'users#logout'
  get '/auth/facebook/callback' => 'users#facebook_login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many  :reviews, dependent: :destroy
    has_many :reviewed_users, through: :reviews, source: :user
    belongs_to :user

    validates_presence_of :title
    validates_presence_of :auther 

    
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :book

    validates_presence_of :description
    validates_presence_of :rating

    def self.positive
        where("rating >= 3")
    end

    def self.negative
        where("rating < 3")
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many  :reviews
    has_many :reviewed_books, through: :reviews, source: :book
    has_many :books, dependent: :destroy

    validates_presence_of :name
    validates :email, uniqueness: true
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
    def logged_in?
        !!current_user
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:auther]
      @auther = Auther.find_by(id: params[:auther])
      if @auther.nil?
        redirect_to authers_path, alert: "auther not found"
      else
        @books = @auther.books
      end
    else
      @books = Book.all
    end
    respond_to do |f|
      f.html{}
      f.json{render json: @books, status: 200}
    end
  end

  def show
    if params[:auther]
      @auther = Auther.find_by(id: params[:auther])
      @book = @auther.books.find_by(id: params[:id])
      if @book.nil?
        redirect_to auther_books_path(@auther), alert: "book not found"
      end
    else
      @book = Book.find(params[:id])
    end
    respond_to do |f|
      f.html{}
      f.json{render json: @book}
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
      @book.update(book_params)

      if @book.save
        redirect_to @book
      else
        render :edit
      end
    else
      flash[:notice] = "you don't own that book."
      redirect_to @book
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
      @book.destroy
      flash[:notice] = "book deleted."
      redirect_to books_path
    else
      flash[:notice] = "you don't own that book."
      redirect_to @book
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :auther)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @book = Book.find(params[:book_id])
    @reviews = @book.reviews
    respond_to do |f|
      f.html{}
      f.json{render json: @reviews, status: 200}
    end
  end

  def show
      @review = Review.find(params[:id])
  end

  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def create
    @book = Book.find(review_params[:book_id])
    @review = current_user.reviews.build(review_params)

    if @review.save
      redirect_to review_path(@review)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end
  def update
    @review = Review.find(params[:id])
    if @review.user_id == current_user.id
      @review.update(review_params)

      if @review.save
        redirect_to @review
      else
        render :edit
      end
    else
      flash[:notice] = "You crazy person, you don't own that!"
      redirect_to @review
    end
  end
    
  def destroy
    @review = Review.find(params[:id])
    if @review.user_id == current_user.id
      @review.destroy
      flash[:notice] = "review deleted."
    else
      flash[:notice] = "You crazy person, you don't own that!"
    end
    redirect_to book_path(@review.book_id)
  end

  private

  def review_params
    params.require(:review).permit(:description, :book_id, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def login_form
    if !logged_in?
      @user = User.new
      render :login
    else
      redirect_to current_user
    end
  end

  def login
    @user = User.find_by(:name => params[:name])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:notice] = "invalid login info"
      render :login
    end
  end

  def facebook_login
    @user = User.find_or_create_by(:email => auth['info']['email'])
    @user.name = auth['info']['name']
    @user.email = auth['info']['email']
    @user.name = auth['info']['name']
    if @user.password == nil
      @user.password = auth['uid']
    end
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to '/login'
    end
  end

  def logout
    session.clear
    redirect_to '/login'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.id == current_user.id
      @user.update(user_params)

      if @user.save
        redirect_to @user
      else
        render :edit
      end
    else
      flash[:notice] = "you don't own that user"
      redirect_to current_user
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.id == current_user.id
      @user.destroy
      session.clear
      flash[:notice] = "user deleted."
      redirect_to '/login'
    else
      flash[:notice] = "you don't own that user"
      redirect_to current_user
    end
  end

  private

  def auth
    request.env['omniauth.auth']
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
 
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1>Editing <%= @book.title %></h1>

<%= form_for @book  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :auther %>
  <%= f.text_field :auther %>
  <br />

  <%= f.submit %>
<% end %>

app/views/books/index.html.erb
<div class="flexbox-container">
    <div>
        <h1>Books</h1>
        <ul id="books">
  
        </ul>
    </div>
    <div>
        <h1>Details</h1>
        <div id="book">
            
        </div>
        <p id="reviews"></p>

        <p id=to_book><%= link_to "To books page"%></p>
    </div>
</div>



<p id=add_book><%= link_to "Add New book"%></p>
<%= button_to "Your user page", user_path(current_user), :method => :get %>

<div id="add_space"></div>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
 
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1>Create a book</h1>

<%= form_for @book  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :auther %>
  <%= f.text_field :auther %><br>

  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<h1><%=@book.title %></h1>
<h3> by <%= @book.auther %></h3>
<br/>
<h2><%=link_to "Reviews", book_reviews_path(@book) %><h2/>
<% @book.reviews.last(3).each do |review| %>
    <h3><%=link_to review.description, book_review_path(@book, review) %><h3/>
<% end %>

<%= button_to "All books", books_path, :method => :get %>
<%= button_to "Edit book", edit_book_path, :method => :get %>

<%= button_to "Add review", new_book_review_path(@book), :method => :get %>

<%if @book.user_id == current_user.id%>
    <%= button_to "delete book", book_path(@book), :method => :delete %>
<%end%>

<h2> reviewed users </h2>
<% @book.reviewed_users.each do |reviewed_user| %>
    <%= reviewed_user.name %>
    <br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= button_to 'logout', logout_path, :method => :delete %>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
 
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1>Editing review</h1>

<%= form_for @review  do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br />
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <br />
  <%= f.submit %>
<% end %>

app/views/reviews/index.html.erb
<h1><%=link_to @book.title, book_path(@book) %><h1/>

<h2>Positive reviews<h2/>
<% @book.reviews.positive.each do |review| %>
    <h3><%= review.description %><h3/>
<% end %>
    

<h2>Negative reviews<h2/>
<% @book.reviews.negative.each do |review| %>
    <h3><%= review.description %><h3/>
<% end %>

app/views/reviews/new.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
 
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1>Create a review</h1>

<%= form_for @review  do |f| %>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
  <br>
  <%= f.label :rating %>
  <br>
  <%= f.number_field 'rating', in: 1..5 %>

  <%= f.hidden_field :book_id, :value => @book.id %>
  <br />

  <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<h1><%= @review.description %></h1>
<h3>rating: <%= '*'*@review.rating %></h3>
<br />
<%= button_to @review.book.title, book_path(@review.book), :method => :get%>
<%= button_to "Edit review", edit_review_path, :method => :get %>

<%= button_to "delete review", review_path(@review), :method => :delete %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1>Editing <%= @user.name %></h1>

<%= form_for @user  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br />

  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/login.html.erb
<h3>Login</h3>
<%= form_tag ({controller: 'users', action: 'login', method: 'post'}) do %>
  name <input name="name">
  <br />
  email <input name="email">
  <br />
  password  <input type="password" name="password">

  <input type="submit" value="login">
<% end %>
<p>
<form method="get" action="/users/new">
  <input type="submit" value="Or sige up">
</form>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1>Create an user</h1>

<%= form_for @user  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br />

  <%= f.submit %>
<% end %>
<%= link_to('Or login with Facebook!', '/auth/facebook') %>
<p/>

<form method="get" action="/login">
  <input type="submit" value="Or login">
</form>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<ul>
  <% @user.reviews.each do |review| %>
    <li><%= link_to review.description, users_path(@user, review) %></li>
  <% end %>
  <form method="get" action="/books">
    <input type="submit" value="To index">
  </form>

  <form method="get" action="/users/<%=@user.id%>/edit">
    <input type="submit" value="Edit user">
  </form>

  <%= button_to 'delete user', user_path(@user), :method => :delete %>
</ul>